version: "3.3"
services:
  nongjang:
    container_name: code
    restart: always
    environment:
      - MODE=prod
    build:
      context: ./nongjang/
      dockerfile: Dockerfile
    command: python manage.py collectstatic
    volumes:
      - django_static:/app/api/nongjang/static

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - django_static:/var/www/django_static
    depends_on:
      - nongjang

volumes:
  django_static:
